name: Publish NuGet Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    
    env:
      Solution_Name: Source\StaX.Domain.sln          
      Wap_Project_Packages: Source\Packages\*.nupkg 
      Wap_Project_Path: Source\StaX.Domain\StaX.Domain.csproj
      Nuget_Api_Key: ${{ secrets.NUGET_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build $env:Solution_Name --configuration Release

      - name: Publish NuGet package
        run: dotnet nuget push $env:Wap_Project_Packages --api-key $env:Nuget_Api_Key --source https://api.nuget.org/v3/index.json
